### ISSUE TITLE
Unable to register usermod in embedded WLED use

### ISSUE THREAD

**Issue by zettseb** [swinbkh/Ambilight2WLED#4]
Hi,
thanks first for your great work! I am trying heavily to bring the Ambilight custom usermod to my WLED compile on ESP2866, so far without success... Can you maybe help me here?

I have added your usermod file to the usermod directory and changed the #include <HTTPClient.h> to #include <ESP8266HTTPClient.h> since the first one could not be found somehow (compilation error).
Then I added the usermod specification in both places in wled00/usermods_list.cpp.
Finally, I created a custom PlatformIO environment based on the d1_mini, which also has
build_flags = ... -D USERMOD_AMBILIGHT
lib_deps = ... ESP8266HTTPClient

Now I am able to compile, and WLED is running on my ESP2866, but the usermods section in the GUI is still empty... :(

**Comment by swinbkh** [comment]
Hi @zettseb, unfortunately I never fully implemented the usermod functionality, instead using a standalone esp32 as my "ambilight to wled interpreter". I couldn't find a way to practically handle dynamically sizeable displays both of the ambilight LEDs, and those of a WLED installation. This project was intended more as a demonstration that the two platforms could be linked using the web APIs. 

I've not progressed with the usermod, since the simple standalone script worked fine for my usage cases, and it may be that the syntax and structure used for usermods has since changed. I've asked for some assistance from the WLED community a few times, but with how niche this usermod is (requiring a user to have a specific brand and feature set enabled TV) there was little motivation to assist, unfortunately. :(
